version: '3'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex-amdgpu
    environment:
      - PLEX_CLAIM=<your Plex claim token>
    volumes:
      - <path to your media files>:/data
      - <path to your Plex config>:/config
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped